name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: login to heroku
      env:
         heroku_api_key: ${{secrets.HEROKU_API_KEY}}

         run: echo "ubuntu-gui" | bash installnovnc
