name: Push Container to Heroku

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: run script
       usedocker: true
       run: bash depend.sh
       
