name: Push Container to Heroku

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: run script
       run: |
          
          export HEROKU_API_KEY=${{secrets.HEROKU_API_KEY}}
          heroku apps
          bash insta*
          
       
